extensions: {}
cabal-file: project.cabal
version: 1
environment: null
module-template: ! 'module MODULE_NAME where

'
ghc-args: []
modules:
  Handlers:
    filename: Handlers.hs
  Contrl.Retry:
    filename: Contrl/Retry.hs
  PushNotify.General.YesodPushAppRoutes:
    filename: PushNotify/General/YesodPushAppRoutes.hs
  PushNotify.Mpns:
    filename: PushNotify/Mpns.hs
  PushNotify.General.YesodPushApp:
    filename: PushNotify/General/YesodPushApp.hs
  PushNotify.Gcm:
    filename: PushNotify/Gcm.hs
  PushNotify.Gcm.Send:
    filename: PushNotify/Gcm/Send.hs
  Import:
    filename: Import.hs
  PushNotify.Mpns.Send:
    filename: PushNotify/Mpns/Send.hs
  PushNotify.General.Send:
    filename: PushNotify/General/Send.hs
  DataBase:
    filename: DataBase.hs
  PushNotify.Mpns.Types:
    filename: PushNotify/Mpns/Types.hs
  PushNotify.Gcm.Types:
    filename: PushNotify/Gcm/Types.hs
  PushNotify.Mpns.Constants:
    filename: PushNotify/Mpns/Constants.hs
  Extra:
    filename: Extra.hs
  PushNotify.Gcm.Constants:
    filename: PushNotify/Gcm/Constants.hs
  Main(Main.hs):
    filename: Main.hs
  Connect4:
    filename: Connect4.hs
  PushNotify.General.Types:
    filename: PushNotify/General/Types.hs
  PushNotify.General:
    filename: PushNotify/General.hs
